name: PR Checks
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Install LLVM 17
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

      - name: "Run PR Check"
        run: make test
